//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_pol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int id { get; set; }
        public string partners { get; set; }
        public string product_partners { get; set; }
        public int quantity { get; set; }
    }
}
