//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_pol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_history
    {
        public int id { get; set; }
        public Nullable<int> PartnersID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int quanty { get; set; }
        public System.DateTime saledate { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
