//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_pol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class skidki
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public string Partner { get; set; }
        public int quantity { get; set; }
        public System.DateTime sale_date { get; set; }
    }
}
